FROM node:8
MAINTAINER dmaxwell351 <dmaxwell351@sent.com>

#COPY docker-entrypoint.sh .

#RUN chmod 777 docker-entrypoint.sh

VOLUME ["/home/nodejs/app"]

#ENTRYPOINT ["docker-entrypoint.sh"]
ENTRYPOINT ["node"]
